name: python_3_7_rtx_6000
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=1.0.0=pyhd8ed1ab_0
  - aiohttp=3.7.0=py37h8f50634_0
  - async-timeout=3.0.1=py_1000
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - black=22.3.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - bottleneck=1.3.4=py37hce1f21e_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15=ha878542_0
  - cached-property=1.5.2=py_0
  - cachetools=5.0.0=pyhd8ed1ab_0
  - cairo=1.14.12=h8948797_3
  - certifi=2022.6.15=py37h89c1867_0
  - cffi=1.15.0=py37hd667e15_1
  - chardet=3.0.4=py37he5f6b98_1008
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=py37h89c1867_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=37.0.1=py37h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py37h540881e_2
  - dask-core=2022.2.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=h48d8840_2
  - debugpy=1.5.1=py37h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py37h06a4308_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonttools=4.33.3=py37h540881e_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.11.0=h70c0345_0
  - fsspec=2022.5.0=pyhd8ed1ab_0
  - geos=3.10.2=h9c3ff4c_0
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h7b6447c_0
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py37heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.6.6=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - graphite2=1.3.13=h58526e2_1001
  - grpcio=1.38.1=py37hb27c1af_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=2.8.0=py37h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imgaug=0.4.0=pyhd8ed1ab_1
  - importlib-metadata=4.11.4=py37h89c1867_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py37h06a4308_0
  - ipython=7.31.1=py37h06a4308_0
  - jasper=2.0.14=hd8c5072_2
  - jedi=0.18.1=py37h06a4308_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jupyter_client=7.2.2=py37h06a4308_0
  - jupyter_core=4.9.2=py37h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.3.2=py37h2527ec5_1
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.10=h9b69904_4
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_0
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.68.4=h3e27bee_0
  - libglu=9.0.0=hf484d3e_1
  - libgomp=11.2.0=h1234567_0
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.18.0=h780b84a_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h74e7548_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.7=pyhd8ed1ab_0
  - matplotlib=3.5.1=py37h06a4308_1
  - matplotlib-base=3.5.1=py37h1058ff1_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py37h06a4308_0
  - multidict=6.0.2=py37h540881e_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py37h89c1867_5
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - nb_black=1.0.7=py_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.5=py37h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.7.1=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.69=hb5efdd6_1
  - numexpr=2.8.1=py37h6abb31d_0
  - numpy=1.21.5=py37he7a7128_2
  - numpy-base=1.21.5=py37hf524024_2
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1o=h166bdaf_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py37h8c16a72_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=6.2.1=py37h34e0f95_0
  - pip=21.2.2=py37h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=2.5.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.18.0=py37hcd2ae1e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-opencv=3.4.2=py37hb342d67_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.4.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h22d08a2_1
  - pysocks=1.7.1=py37_1
  - python=3.7.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.3.0=py37hda87dfa_1
  - pyyaml=6.0=py37h540881e_4
  - pyzmq=22.3.0=py37h295c915_2
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.8=pyhd8ed1ab_0
  - scikit-image=0.16.2=py37hb3f55d8_0
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37hc147768_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - setuptools=61.2.0=py37h06a4308_0
  - shapely=1.8.2=py37h8998c72_1
  - sip=6.5.1=py37h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=hc218d9a_0
  - sympy=1.10.1=py37h06a4308_0
  - tensorboard=2.9.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py37h38fbfac_2
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h1ccaba5_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - torchaudio=0.11.0=py37_cu113
  - torchvision=0.2.1=py37_0
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typed-ast=1.5.3=py37h540881e_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - unicodedata2=14.0.0=py37h540881e_1
  - urllib3=1.26.9=py37h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.1.2=pyhd8ed1ab_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.6.0=py37h8f50634_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - anykeystore==0.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asgiref==3.5.2
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - caldav==0.1.4
    - clip==1.0
    - contextlib2==21.6.0
    - coverage==6.4.1
    - cryptacular==1.6.2
    - defusedxml==0.7.1
    - django==3.2.13
    - fastjsonschema==2.15.3
    - ftfy==6.1.1
    - greenlet==1.1.2
    - hupper==1.10.3
    - importlib-resources==5.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - jinja2==3.1.2
    - jsonschema==4.6.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.1
    - lxml==4.9.0
    - markupsafe==2.1.1
    - mistune==0.8.4
    - ml-collections==0.1.1
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nose==1.3.7
    - notebook==6.4.12
    - pandocfilters==1.5.0
    - pastedeploy==2.1.1
    - pbkdf2==1.3
    - plaster==1.0
    - plaster-pastedeploy==0.7
    - prometheus-client==0.14.1
    - pyramid==2.0
    - pyramid-mailer==0.15.1
    - pyrsistent==0.18.1
    - python3-openid==3.2.0
    - regex==2022.7.9
    - repoze-sendmail==4.4.1
    - send2trash==1.8.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.4.37
    - sqlparse==0.4.2
    - terminado==0.15.0
    - timm==0.5.4
    - tinycss2==1.1.1
    - transaction==3.0.1
    - translationstring==1.4
    - velruse==1.1.1
    - venusian==3.0.0
    - vobject==0.9.6.1
    - webencodings==0.5.1
    - webob==1.8.7
    - widgetsnbextension==3.6.1
    - wtforms==3.0.1
    - wtforms-recaptcha==0.3.2
    - zope-deprecation==4.4.0
    - zope-interface==5.4.0
    - zope-sqlalchemy==1.6
